mode            server
tx_burst        128
launch_num      4
cpu             1

payload_size    1
duration        35s

# pci             local_ip       peer_ip         peer_mac
port            0000:07:00.0    198.18.2.3     198.18.2.1     a8:b8:e0:09:fe:bd

client          198.18.2.10     16
server          198.18.2.3      1
listen          80              32
