mode            server
tx_burst        128
launch_num      4
cpu             1

payload_size    1
duration        10m

# pci             local_ip       gateway
port            0000:03:00.0    198.19.0.2    198.19.0.1

# addr_start      count
client          198.18.0.2      100
server          198.19.0.2      1

# port_start      count
listen          80              16
