mode            client
launch_num      1
cpu             1
duration        2s
cps             1
cc              1
keepalive       1s
payload_size    1

port            0000:03:00.0    198.18.0.2    198.18.0.1    02:00:00:00:00:01
client          198.18.0.2      1
server          198.19.0.2      1
listen          80              1
