- version: 2
  interfaces: ['0000:07:00.0', '0000:08:00.0']
  port_info:
    - src_mac:  [0xa8, 0xb8, 0xe0, 0x09, 0xfe, 0xbd]
      dest_mac: [0xa8, 0xb8, 0xe0, 0x09, 0xfe, 0xa1]
    - src_mac:  [0xa8, 0xb8, 0xe0, 0x09, 0xfe, 0xbe]
      dest_mac: [0xa8, 0xb8, 0xe0, 0x09, 0xfe, 0xa2]
  platform:
    master_thread_id: 0
    latency_thread_id: 1
    dual_if:
      - socket: 0
        threads: [2, 3, 4, 5]

