- version: 2
  interfaces: ['03:00.0', '04:00.0']
  port_info:
    - ip: 198.18.0.2
      default_gw: 198.18.0.1
    - ip: 198.19.0.2
      default_gw: 198.19.0.1
  platform:
    master_thread_id: 0
    latency_thread_id: 1
    dual_if:
      - socket: 0
        threads: [2, 3, 4, 5, 6, 7]
